"""
ConstructIQ High-Fidelity PDF Report Generator.
Uses ReportLab to create professional construction estimation documents.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from datetime import datetime
import io

def generate_estimation_report(project_name: str, geometry: dict, materials: dict, labour: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.5*cm, leftMargin=1.5*cm,
        topMargin=2*cm, bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()
    
    # Custom Styles
    brand_blue = colors.Color(0.06, 0.45, 0.81) # #0E73CF
    title_style = ParagraphStyle(
        'BrandTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=brand_blue,
        spaceAfter=20
    )
    section_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.black,
        borderPadding=(0, 0, 0, 5),
        borderWidth=0,
        spaceBefore=15,
        spaceAfter=10
    )

    elements = []

    # 1. Header
    elements.append(Paragraph(f"Material Estimation Report", title_style))
    elements.append(Paragraph(f"Project: {project_name}", styles['Normal']))
    elements.append(Paragraph(f"Date: {datetime.now().strftime('%d %b %Y')}", styles['Normal']))
    elements.append(Spacer(1, 15))

    # 2. Executive Summary (Geometry)
    elements.append(Paragraph("Drawing Analysis (Geometric Breakdown)", section_style))
    geo_data = [
        ["Structural Element", "Identified Value", "Unit"],
        ["Total Floor Area", f"{geometry.get('totalFloorArea', 0):.2f}", "m²"],
        ["Wall Surface Area", f"{geometry.get('totalWallArea', 0):.2f}", "m²"],
        ["Building Height", f"{geometry.get('buildingHeight', 0):.1f}", "m"],
        ["Door Units", f"{geometry.get('doorCount', 0)}", "nos"],
        ["Window Units", f"{geometry.get('windowCount', 0)}", "nos"],
        ["Structural Volume", f"{geometry.get('structuralVolume', 0):.2f}", "m³"],
    ]
    t_geo = Table(geo_data, colWidths=[6*cm, 6*cm, 4*cm])
    t_geo.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), brand_blue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t_geo)
    elements.append(Spacer(1, 20))

    # 3. Bill of Quantities (Materials)
    elements.append(Paragraph("Bill of Quantities (Estimated Materials)", section_style))
    mat_data = [["Resource", "Quantity", "Unit", "Category"]]
    for key, val in materials.items():
        if key == "metadata": continue
        mat_data.append([
            key.capitalize(),
            str(val.get('quantity', 0)),
            val.get('unit', ''),
            "Structural"
        ])
    
    t_mat = Table(mat_data, colWidths=[5*cm, 4*cm, 3*cm, 4*cm])
    t_mat.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t_mat)
    elements.append(Spacer(1, 20))

    # 4. Labour Productivity Analysis
    elements.append(Paragraph("Labour Productivity Analysis (CPWD Norms)", section_style))
    lab_data = [["Trade / Activity", "Effort", "Norm Applied"]]
    for key, val in labour.items():
        lab_data.append([
            val.get('trade', key.replace('_', ' ').title()),
            f"{val.get('labour_days', 0)} man-days",
            val.get('norm', '')
        ])
    
    t_lab = Table(lab_data, colWidths=[6*cm, 4*cm, 6*cm])
    t_lab.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.whitesmoke),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t_lab)

    # Footer
    elements.append(Spacer(1, 30))
    elements.append(Paragraph("Disclaimer: This report is generated by ConstructIQ AI based on extracted CAD geometry. Actual quantities may vary by 5-10% depending on site conditions.", styles['Italic']))

    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
