import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class ReportGenerator {
  static Future<void> generateProjectReport({
    required String projectName,
    required String managerName,
    required Map<String, dynamic> summary,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) => pw.Padding(
          padding: const pw.EdgeInsets.all(32),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(level: 0, child: pw.Text('Construction Intelligence System - Project Report')),
              pw.SizedBox(height: 20),
              pw.Text('Date: ${DateTime.now().toLocal()}'),
              pw.Text('Project: $projectName'),
              pw.Text('Manager: $managerName'),
              pw.Divider(),
              pw.SizedBox(height: 20),
              pw.Header(level: 1, child: pw.Text('Material Summary')),
              pw.Table.fromTextArray(
                context: context,
                data: [
                  ['Material', 'Estimate', 'Actual', 'Deviation'],
                  ['Cement', '${summary['est_cement']}', '${summary['act_cement']}', '${summary['dev_cement']}%'],
                  ['Sand', '${summary['est_sand']}', '${summary['act_sand']}', '${summary['dev_sand']}%'],
                  ['Bricks', '${summary['est_bricks']}', '${summary['act_bricks']}', '${summary['dev_bricks']}%'],
                ],
              ),
              pw.SizedBox(height: 40),
              pw.Text('AI Prediction: ${summary['recommendation']}'),
              pw.Spacer(),
              pw.Center(child: pw.Text('Generated by Construction AI platform - 8th Sem Project')),
            ],
          ),
        ),
      ),
    );

    // Show print preview
    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }
}
